"""The custom-window Windows installer.

The same job as the MUI2 script in `build.py` — files, shortcuts, registry,
uninstaller — behind the window the user approved after four rounds of the
preview (`installer-preview.nsi`, context.md §3.58 and §3.61).

**It is published beside the MUI2 installer, not instead of it.** The user's
instruction: *"you can make that custom installer too but before push it for
later release instead of old installer let me test it then when i told you you
can replace the old one with the custom one."* So it is an extra asset called
`…-windows-x64-custom-installer.exe`, and the name deliberately avoids the word
*setup*: `Release.asset()` returns the first published file whose name contains
every piece it was given, and an updating build asks for
`("windows", "setup", ".exe")`. A custom installer that matched that could be
handed to a machine as its update, which is not something to leave to the order
GitHub happens to list assets in.

Placeholders are `@NAME@` and substituted with `str.replace`, not `str.format`.
An NSIS script is mostly `${...}`, and a format string would need every one of
them doubled — which is a transcription error waiting to happen in a file that
cannot be run here.

What differs from the preview, which installed nothing:

* **MultiUser drives the mode**, so "everyone" elevates and writes to HKLM and
  "just me" does not. The cards set it; the folder box still wins, because
  somebody who types a path means it.
* **Page two is the real `instfiles` page**, restyled. Controls cannot be added
  to it through nsDialogs (§3.61), so it has the colours, the accent progress
  bar and the panel's colour block down the left, but not the step list. It is
  on screen for about twenty seconds.
* **The install section is the MUI2 one**, including closing a running copy
  before writing (§437) and reopening the application through Explorer after a
  silent update (§458).
"""

from __future__ import annotations

from pathlib import Path

_SCRIPT = r"""
; Generated by packaging/installer_custom.py — do not edit in dist/.
Unicode true

!include "nsDialogs.nsh"
!include "LogicLib.nsh"
!include "WinMessages.nsh"
!include "FileFunc.nsh"

!define MULTIUSER_EXECUTIONLEVEL Highest
!define MULTIUSER_INSTALLMODE_COMMANDLINE
!define MULTIUSER_INSTALLMODE_INSTDIR "@APP_SLUG@"
!define MULTIUSER_INSTALLMODE_INSTALL_REGISTRY_KEY "Software\@APP_SLUG@"
!define MULTIUSER_INSTALLMODE_INSTALL_REGISTRY_VALUENAME "InstallDir"
!define MULTIUSER_INSTALLMODE_DEFAULT_REGISTRY_KEY "Software\@APP_SLUG@"
!define MULTIUSER_INSTALLMODE_DEFAULT_REGISTRY_VALUENAME "InstallDir"
!define MULTIUSER_INSTALLMODE_FUNCTION OnInstallModeChanged
!include "MultiUser.nsh"

Name "@APP_NAME@"
OutFile "@OUTPUT@"
Caption "@APP_NAME@"
BrandingText " "
Icon "@ICON@"
XPStyle on
ShowInstDetails show

!define WIN_W 720
!define WIN_H 460
!define PANEL_W 250
; One corner radius for every light box on every page. They were 11, 11 and 9,
; typed at three different times; asked for softer and consistent.
!define RADIUS  14
!define TICKS @TICKS@

; Straight out of ixd/ui/theme.py, so the installer and the application are the
; same object rather than two things that resemble each other.
!define C_BG      0x0D0F16
!define C_PANEL   0x0A0C12
!define C_SURFACE 0x141827
!define C_CARD    0x181D2F
!define C_TEXT    0xE7ECFF
!define C_DIM     0x95A0C2
!define C_FAINT   0x6B7597
!define C_ACCENT  0x5B8CFF
!define C_GOOD    0x43D6A0
!define C_WHITE   0xFFFFFF

!ifndef GWL_STYLE
  !define GWL_STYLE -16
!endif
!ifndef GWL_EXSTYLE
  !define GWL_EXSTYLE -20
!endif
!ifndef WS_EX_WINDOWEDGE
  !define WS_EX_WINDOWEDGE 0x00000100
!endif
!ifndef WS_EX_CLIENTEDGE
  !define WS_EX_CLIENTEDGE 0x00000200
!endif
!define WS_CHROME        0x00CF0000
!define SWP_FRAMECHANGED 0x0020
!define SWP_NOZORDER     0x0004
!define SWP_NOMOVE       0x0002
!define SWP_NOSIZE       0x0001
!define IXD_HWND_BOTTOM  1
!define IXD_HWND_TOP     0
!define SWP_QUIET        0x0013   ; NOSIZE | NOMOVE | NOACTIVATE
!define SWP_NOACTIVATE   0x0010
; NOACTIVATE | NOCOPYBITS. Growing a window, Windows copies the bits it thinks
; are still valid and invalidates only the rest — and it works that out from
; the window region as it stood *before* this step replaced it. NOCOPYBITS
; gives up the optimisation and invalidates the lot, which is what a control
; whose region changes on every step needs.
!define SWP_BARSTEP      0x0110
; INVALIDATE | ERASE | ALLCHILDREN | UPDATENOW
!define RDW_WHOLE        0x0185
; INVALIDATE | ERASE | UPDATENOW — one window, painted before the call
; returns, and nothing else invited to repaint with it. `RDW_WHOLE` on the
; page would bring the full-page backdrop along, and on this page that is the
; control that can wipe everything else (§3.75).
!define RDW_NOW          0x0105
; **`WS_CLIPSIBLINGS` does not belong here, and it was measured out again.**
; Page one's cards and dots round; page two's are square to the pixel through
; the same `RoundCorners`, and the one style bit that differs is nsDialogs'
; `WS_CLIPSIBLINGS` (nsDialogs.nsh:251). Adding it to `RawCtl` **emptied the
; page**: `l2.png` is 97.1% bare background, the panel's colour absent
; altogether, and the only thing still drawn is control 1006 — NSIS's own,
; and the only control on the page without the bit.
;
; This page has a full-page backdrop `STATIC` as a sibling of everything else,
; and a `CS_PARENTDC` control that is clipped against an overlapping sibling
; covering the whole page is clipped to nothing. §3.75 has the measurements.
; Do not add it back without a screenshot of the result.
!define RAW_STYLE        0x50000000   ; CHILD | VISIBLE
!define SS_BITMAPCTL     0x0000000E
!ifndef IMAGE_BITMAP
  !define IMAGE_BITMAP   0
!endif
!ifndef LR_LOADFROMFILE
  !define LR_LOADFROMFILE 0x0010
!endif
!ifndef GW_HWNDNEXT
  !define GW_HWNDNEXT    2
!endif
!ifndef GW_CHILD
  !define GW_CHILD       5
!endif
!ifndef SM_CXSCREEN
  !define SM_CXSCREEN 0
!endif
!ifndef SM_CYSCREEN
  !define SM_CYSCREEN 1
!endif
; SS_CENTER|SS_CENTERIMAGE, precomputed: ${NSD_AddStyle} hands its argument to
; System::Int64Op, which takes a number and not an expression.
!define SS_BUTTONTEXT 0x00000201
!define EC_BOTHMARGINS 0x0003

; SC_MOVE (0xF010) with HTCAPTION (2). Sent to a window, it puts Windows into
; its own move loop — the way dragging a title bar does, except that it can be
; started from anywhere.
;
; This is what makes a borderless window movable **without a plugin**. The
; header of this file used to say it could not be done: answering WM_NCHITTEST
; needs a window procedure, and NSIS has no way to subclass a window. True, and
; beside the point — Windows will move a window on request, and asking is a
; `SendMessage`. Reported as "the window is not moveable when i try to move it
; from center of the screen", which is a fair thing to expect of a window.
;
; One honest difference from a title bar: a label reports its click on button
; *up* (STN_CLICKED), so the move loop begins after the button is released.
; The window then follows the mouse until the next click puts it down, rather
; than being dragged with the button held.
!define SC_DRAGMOVE 0xF012

; Kept as a note rather than a constant, because the lesson outlives the code
; that needed it: raw Win32 colour messages take a **COLORREF**, 0x00BBGGRR,
; and not the RGB `SetCtlColors` accepts. C_ACCENT (0x5B8CFF) handed to
; PBM_SETBARCOLOR paints 0xFF8C5B — an orange bar in a blue application.

Var Dialog
Var FontH1
Var FontBody
Var FontSmall
Var FontButton
Var CardUser
Var CardAll
Var CardUserDot
Var CardAllDot
Var CardUserTitle
Var CardUserSub
Var CardAllTitle
Var CardAllSub
Var FolderCard
Var FolderText
Var Step
Var Tmp
Var StartNow
Var StartBox
Var PageHwnd
Var BarFill
Var Ticks

!macro RoundCorners hwnd w h radius
  System::Call 'gdi32::CreateRoundRectRgn(i 0, i 0, i ${w}, i ${h}, i ${radius}, i ${radius}) p .s'
  Pop $Tmp
  System::Call 'user32::SetWindowRgn(p ${hwnd}, p $Tmp, i 1)'
!macroend

!macro Place hwnd x y w h
  System::Call 'user32::MoveWindow(p ${hwnd}, i ${x}, i ${y}, i ${w}, i ${h}, i 1)'
!macroend

!macro Font hwnd font
  SendMessage ${hwnd} ${WM_SETFONT} ${font} 1
!macroend

!macro Label var text x y w h font fg bg
  ${NSD_CreateLabel} 0 0 10u 10u "${text}"
  Pop ${var}
  SetCtlColors ${var} ${fg} ${bg}
  !insertmacro Font ${var} ${font}
  !insertmacro Place ${var} ${x} ${y} ${w} ${h}
!macroend

!macro Fill var x y w h radius colour
  ${NSD_CreateLabel} 0 0 10u 10u ""
  Pop ${var}
  SetCtlColors ${var} ${colour} ${colour}
  !insertmacro Place ${var} ${x} ${y} ${w} ${h}
  !insertmacro RoundCorners ${var} ${w} ${h} ${radius}
!macroend

; Every button here is a label. SetCtlColors answers WM_CTLCOLOR*, and a real
; push button ignores the brush it is handed and paints its own face — the
; Browse button asked for the dark surface and Windows drew it stock white
; (context.md §3.58). nsDialogs gives every label SS_NOTIFY, so it reports its
; own clicks and needs nothing else.
!macro Pill var text x y w h fg bg onclick
  ${NSD_CreateLabel} 0 0 10u 10u "${text}"
  Pop ${var}
  ${NSD_AddStyle} ${var} ${SS_BUTTONTEXT}
  SetCtlColors ${var} ${fg} ${bg}
  !insertmacro Font ${var} $FontButton
  !insertmacro Place ${var} ${x} ${y} ${w} ${h}
  !insertmacro RoundCorners ${var} ${w} ${h} 9
  ${NSD_OnClick} ${var} ${onclick}
!macroend

; ---------------------------------------------------------------------------
; Controls on a page nsDialogs is not driving
;
; The header of this file used to say the instfiles page could not take
; controls of ours. What it could not take is `${NSD_Create*}`, which needs a
; dialog `nsDialogs::Create` made — and creating one on that page would destroy
; the very controls the install writes to. `CreateWindowExW` needs none of
; that: a STATIC parented to the page's own dialog is a child like any other,
; and `SetCtlColors` reaches it because NSIS answers WM_CTLCOLOR* by reading
; the *control's* window data, whichever of its pages the control is on.
;
; That is the whole of §3.61's obstacle, and it cost page two three rounds of
; screenshots — a borrowed progress bar that came out black, on a page with
; nothing else on it. See the note above PageInstallShow.
!macro RawCtl var class text style x y w h
  System::Call 'user32::CreateWindowExW(i 0, w "${class}", w "${text}", \
      i ${style}, i ${x}, i ${y}, i ${w}, i ${h}, p $PageHwnd, p 0, p 0, p 0) p .s'
  Pop ${var}
!macroend

; **A picture instead of a shape.** `RoundCorners` cannot round a `STATIC`:
; the class is registered `CS_PARENTDC`, so the control paints its whole
; rectangle whatever region it was given, and the one style bit that changes
; that empties this page (§3.75). Anything on page two that has to be round is
; therefore drawn by `packaging/installer_art.py` with the colour behind it
; already in the pixels, and shown by a control that only blits.
!macro RawPicture var file x y w h
  System::Call 'user32::LoadImageW(p 0, w "$PLUGINSDIR\${file}", \
      i ${IMAGE_BITMAP}, i 0, i 0, i ${LR_LOADFROMFILE}) p .r4'
  IntOp $5 ${RAW_STYLE} | ${SS_BITMAPCTL}
  !insertmacro RawCtl ${var} "STATIC" "" $5 ${x} ${y} ${w} ${h}
  SendMessage ${var} ${STM_SETIMAGE} ${IMAGE_BITMAP} $4
!macroend

!macro RawFill var x y w h colour
  !insertmacro RawCtl ${var} "STATIC" "" ${RAW_STYLE} ${x} ${y} ${w} ${h}
  SetCtlColors ${var} ${colour} ${colour}
!macroend

!macro RawLabel var text x y w h font fg bg
  !insertmacro RawCtl ${var} "STATIC" "${text}" ${RAW_STYLE} ${x} ${y} ${w} ${h}
  SetCtlColors ${var} ${fg} ${bg}
  !insertmacro Font ${var} ${font}
!macroend

; Z-order is stated, never inferred: a child window's place among its siblings
; depends on creation order in a way this project has already been wrong about
; twice (§3.61).
!macro ToBottom hwnd
  System::Call 'user32::SetWindowPos(p ${hwnd}, p ${IXD_HWND_BOTTOM}, \
      i 0, i 0, i 0, i 0, i ${SWP_QUIET})'
!macroend

!macro ToTop hwnd
  System::Call 'user32::SetWindowPos(p ${hwnd}, p ${IXD_HWND_TOP}, \
      i 0, i 0, i 0, i 0, i ${SWP_QUIET})'
!macroend

Function OnInstallModeChanged
  ; A remembered installation wins. MultiUser calls this whenever the mode is
  ; set, including from MULTIUSER_INIT — which runs after it has read the
  ; previous InstallDir out of the registry. Overwriting $INSTDIR here threw
  ; that away, so an upgrade never targeted the folder the user installed into
  ; (session-log §455). SHCTX follows the mode, so this reads the hive the
  ; Install section wrote to.
  ClearErrors
  ReadRegStr $0 SHCTX "Software\@APP_SLUG@" "InstallDir"
  ${IfNot} ${Errors}
  ${AndIf} $0 != ""
    StrCpy $INSTDIR "$0"
    Return
  ${EndIf}
  ${If} $MultiUser.InstallMode == "AllUsers"
    StrCpy $INSTDIR "$PROGRAMFILES64\@APP_SLUG@"
  ${Else}
    StrCpy $INSTDIR "$APPDATA\@APP_SLUG@"
  ${EndIf}
FunctionEnd

Function .onInit
  !insertmacro MULTIUSER_INIT
  InitPluginsDir
  File /oname=$PLUGINSDIR\mark.bmp "@ART@\mark.bmp"
  File /oname=$PLUGINSDIR\tick.bmp "@ART@\tick.bmp"
  ; Page two's rounded rectangles, drawn at build time by
  ; packaging/installer_art.py because a region on a STATIC does not round it
  ; (§3.75). The colour behind each is baked in; there is no alpha in a BMP.
  File /oname=$PLUGINSDIR\card.bmp "@ART@\card.bmp"
  File /oname=$PLUGINSDIR\dot-good.bmp "@ART@\dot-good.bmp"
  File /oname=$PLUGINSDIR\dot-accent.bmp "@ART@\dot-accent.bmp"
  File /oname=$PLUGINSDIR\dot-faint.bmp "@ART@\dot-faint.bmp"
FunctionEnd

Function un.onInit
  !insertmacro MULTIUSER_UNINIT
FunctionEnd

Function .onGUIInit
  ; Strip the title bar and the resize frame, then size and centre what is
  ; left. NSIS gives no way to ask for a window like this.
  System::Call 'user32::GetWindowLongW(p $HWNDPARENT, i ${GWL_STYLE}) i .r0'
  IntOp $1 ${WS_CHROME} ~
  IntOp $0 $0 & $1
  System::Call 'user32::SetWindowLongW(p $HWNDPARENT, i ${GWL_STYLE}, i r0)'

  System::Call 'user32::GetSystemMetrics(i ${SM_CXSCREEN}) i .r2'
  System::Call 'user32::GetSystemMetrics(i ${SM_CYSCREEN}) i .r3'
  IntOp $2 $2 - ${WIN_W}
  IntOp $2 $2 / 2
  IntOp $3 $3 - ${WIN_H}
  IntOp $3 $3 / 2
  IntOp $4 ${SWP_FRAMECHANGED} | ${SWP_NOZORDER}
  System::Call 'user32::SetWindowPos(p $HWNDPARENT, p 0, i r2, i r3, \
      i ${WIN_W}, i ${WIN_H}, i r4)'
  !insertmacro RoundCorners $HWNDPARENT ${WIN_W} ${WIN_H} 14

  ; The panel's colour, not the page's. The instfiles page cannot take controls
  ; of ours (§3.61), so it is inset to the content area instead and this shows
  ; through on its left — the colour block is continuous across all three pages
  ; even though the step list is only on the two that are ours.
  SetCtlColors $HWNDPARENT ${C_TEXT} ${C_PANEL}

  GetDlgItem $0 $HWNDPARENT 1018
  !insertmacro Place $0 0 0 ${WIN_W} ${WIN_H}
  GetDlgItem $0 $HWNDPARENT 1028
  ShowWindow $0 ${SW_HIDE}
  GetDlgItem $0 $HWNDPARENT 1256
  ShowWindow $0 ${SW_HIDE}

  CreateFont $FontH1     "Segoe UI" 15 600
  CreateFont $FontBody   "Segoe UI" 10 400
  CreateFont $FontSmall  "Segoe UI" 9  400
  CreateFont $FontButton "Segoe UI" 10 600

  Call HideStockButtons
  Call HideParentChrome
  StrCpy $Step 0
  StrCpy $StartNow 1

  ; **This is what carries page two into page three.** The install page's Next
  ; is hidden like the other two, so when the copy finished there was no way
  ; forward but Tab to the invisible button and Enter — reported exactly that
  ; way, twice.
  ;
  ; Posting WM_COMMAND/IDOK from the end of the install section was the first
  ; answer and it cannot work: the section runs on NSIS's install thread, and
  ; NSIS re-enables IDOK only *after* that thread ends, so the message always
  ; arrives at a disabled button and is dropped. No amount of ordering inside
  ; the section fixes that.
  ;
  ; `SetAutoClose true` is the hook that fires on the right side of that line,
  ; and it is not a guess: it is how MUI2 gets from its progress page to its
  ; finish page — `Contrib/Modern UI 2/Pages/Finish.nsh`, in the page's own
  ; GUIInit, which is this function.
  SetAutoClose true
FunctionEnd

; NSIS's three buttons are never shown. They cannot take our colours, and they
; sit under a page dialog that covers the window; the pills post WM_COMMAND to
; the parent instead, which is what clicking them would have sent.
; NSIS's outer window has furniture of its own, and hiding it by id was
; hiding the two ids this script happened to know. What was left is an etched
; separator — measured off the user's screenshot twice: two rows, 0xA0A0A0 over
; 0xFFFFFF, 291 px wide and inset 11 px, which is `SS_ETCHEDHORZ` drawing
; COLOR_3DSHADOW over COLOR_3DHIGHLIGHT and nothing else in Windows looks like
; that. It survived hiding every child of the *page* because it is a child of
; the parent.
;
; So: every child of the parent goes, except the page dialogs themselves —
; class `#32770` — which are the only children this installer draws into.
; Knowing no ids is the point; NSIS's template is free to hold whatever it
; likes.
Function HideParentChrome
  System::Call 'user32::GetWindow(p $HWNDPARENT, i ${GW_CHILD}) p .r1'
  ${Do}
    ${If} $1 == 0
      ${ExitDo}
    ${EndIf}
    ; 1018 is the placeholder whose rectangle NSIS puts each page dialog over.
    ; It draws nothing, and it is exempt because hiding the thing that defines
    ; where the pages go is not a risk worth taking to remove a line.
    System::Call 'user32::GetDlgCtrlID(p $1) i .r3'
    System::Call 'user32::GetClassNameW(p $1, t .r2, i 64) i'
    ${If} $2 != "#32770"
    ${AndIf} $3 != 1018
      ShowWindow $1 ${SW_HIDE}
    ${EndIf}
    System::Call 'user32::GetWindow(p $1, i ${GW_HWNDNEXT}) p .r1'
  ${Loop}
FunctionEnd

Function HideStockButtons
  GetDlgItem $0 $HWNDPARENT 1
  ShowWindow $0 ${SW_HIDE}
  GetDlgItem $0 $HWNDPARENT 2
  ShowWindow $0 ${SW_HIDE}
  GetDlgItem $0 $HWNDPARENT 3
  ShowWindow $0 ${SW_HIDE}
FunctionEnd

Function GoNext
  Pop $0
  SendMessage $HWNDPARENT ${WM_COMMAND} 1 0
FunctionEnd

Function GoCancel
  Pop $0
  SendMessage $HWNDPARENT ${WM_COMMAND} 2 0
FunctionEnd

Function OnClose
  Pop $0
  SendMessage $HWNDPARENT ${WM_CLOSE} 0 0
FunctionEnd

; Grab anywhere on the panel or the strip above the content and the window
; moves. Both are the parts with nothing else to click on, which is exactly
; where somebody reaches for a window that has no title bar.
Function DragWindow
  Pop $0
  SendMessage $HWNDPARENT ${WM_SYSCOMMAND} ${SC_DRAGMOVE} 0
FunctionEnd

Function BrandPanel
  !insertmacro Fill $0 0 0 ${PANEL_W} ${WIN_H} 0 ${C_PANEL}
  ${NSD_OnClick} $0 DragWindow

  ; A grab strip across the top of the content side, where a title bar would
  ; be. Transparent to look at — it carries the background colour — and it is
  ; created before everything else on this page so nothing it would cover has
  ; been made yet.
  ${NSD_CreateLabel} 0 0 10u 10u ""
  Pop $0
  SetCtlColors $0 ${C_BG} ${C_BG}
  !insertmacro Place $0 ${PANEL_W} 0 470 34
  ${NSD_OnClick} $0 DragWindow

  ${NSD_CreateBitmap} 0 0 10u 10u ""
  Pop $0
  ${NSD_SetImage} $0 "$PLUGINSDIR\mark.bmp" $1
  !insertmacro Place $0 28 34 40 40

  ; 26px boxes, 26px apart: at 15pt Segoe UI a 20px box cut the letters through
  ; their descenders and the two lines collided.
  !insertmacro Label $1 "Internet Xtreme" 28 84 200 26 $FontH1 ${C_TEXT} ${C_PANEL}
  !insertmacro Label $1 "Downloader" 28 110 200 26 $FontH1 ${C_TEXT} ${C_PANEL}
  !insertmacro Label $1 "Version @VERSION@" 28 144 200 18 $FontSmall ${C_FAINT} ${C_PANEL}

  StrCpy $2 0
  StrCpy $3 200
  ${Do}
    ${If} $2 == 0
      StrCpy $4 "Where it goes"
    ${ElseIf} $2 == 1
      StrCpy $4 "Installing"
    ${Else}
      StrCpy $4 "Ready"
    ${EndIf}

    ; Every colour is a literal. SetCtlColors reads its arguments at compile
    ; time, so `SetCtlColors $6 $5 $5` compiles and paints black.
    ${NSD_CreateLabel} 0 0 10u 10u ""
    Pop $6
    ${If} $2 < $Step
      SetCtlColors $6 ${C_GOOD} ${C_GOOD}
    ${ElseIf} $2 == $Step
      SetCtlColors $6 ${C_ACCENT} ${C_ACCENT}
    ${Else}
      SetCtlColors $6 ${C_FAINT} ${C_FAINT}
    ${EndIf}
    IntOp $7 $3 + 4
    !insertmacro Place $6 28 $7 11 11
    !insertmacro RoundCorners $6 11 11 11

    ${NSD_CreateLabel} 0 0 10u 10u "$4"
    Pop $6
    ${If} $2 == $Step
      SetCtlColors $6 ${C_TEXT} ${C_PANEL}
      StrCpy $8 $FontButton
    ${ElseIf} $2 < $Step
      SetCtlColors $6 ${C_DIM} ${C_PANEL}
      StrCpy $8 $FontBody
    ${Else}
      SetCtlColors $6 ${C_FAINT} ${C_PANEL}
      StrCpy $8 $FontBody
    ${EndIf}
    !insertmacro Font $6 $8
    !insertmacro Place $6 52 $3 180 20

    IntOp $3 $3 + 44
    IntOp $2 $2 + 1
  ${LoopUntil} $2 >= 3

  !insertmacro Label $1 "No ffmpeg. No yt-dlp. No telemetry." \
      28 420 210 16 $FontSmall ${C_FAINT} ${C_PANEL}

  ; No `$` in front of the glyph: NSIS reads `$x` as a variable and drops it.
  ${NSD_CreateLabel} 0 0 10u 10u "✕"
  Pop $0
  ${NSD_AddStyle} $0 ${SS_BUTTONTEXT}
  SetCtlColors $0 ${C_DIM} ${C_BG}
  !insertmacro Font $0 $FontBody
  !insertmacro Place $0 664 16 28 28
  ${NSD_OnClick} $0 OnClose
FunctionEnd

; ---------------------------------------------------------------------------
; Page one — where it goes
; ---------------------------------------------------------------------------
Function PageWhere
  StrCpy $Step 0
  nsDialogs::Create 1018
  Pop $Dialog
  SetCtlColors $Dialog ${C_TEXT} ${C_BG}
  Call HideStockButtons
  Call HideParentChrome
  Call BrandPanel

  !insertmacro Label $0 "Where should it go?" 284 44 380 30 $FontH1 ${C_TEXT} ${C_BG}
  !insertmacro Label $0 "Two answers, and they are not the same choice." \
      284 78 380 20 $FontBody ${C_DIM} ${C_BG}

  !insertmacro Fill $CardUser 284 118 402 62 ${RADIUS} ${C_CARD}
  ${NSD_OnClick} $CardUser OnPickUser
  !insertmacro Fill $CardUserDot 306 141 16 16 16 ${C_ACCENT}
  !insertmacro Label $CardUserTitle "Just me" 332 130 340 20 $FontButton ${C_TEXT} ${C_CARD}
  ${NSD_OnClick} $CardUserTitle OnPickUser
  !insertmacro Label $CardUserSub "No administrator needed  ·  %APPDATA%\@APP_SLUG@" \
      332 151 340 18 $FontSmall ${C_DIM} ${C_CARD}
  ${NSD_OnClick} $CardUserSub OnPickUser

  !insertmacro Fill $CardAll 284 190 402 62 ${RADIUS} ${C_SURFACE}
  ${NSD_OnClick} $CardAll OnPickAll
  !insertmacro Fill $CardAllDot 306 213 16 16 16 ${C_FAINT}
  !insertmacro Label $CardAllTitle "Everyone on this PC" 332 202 340 20 $FontButton ${C_TEXT} ${C_SURFACE}
  ${NSD_OnClick} $CardAllTitle OnPickAll
  !insertmacro Label $CardAllSub "Needs administrator  ·  Program Files" \
      332 223 340 18 $FontSmall ${C_DIM} ${C_SURFACE}
  ${NSD_OnClick} $CardAllSub OnPickAll

  !insertmacro Label $0 "FOLDER" 284 274 200 16 $FontSmall ${C_DIM} ${C_BG}

  ; The box first, its card afterwards, and the card pushed to the bottom of
  ; the z-order explicitly. A label carries WS_EX_TRANSPARENT and paints after
  ; the windows beneath it; stripping that is not enough either, because the
  ; earlier-created control is the one on top. Both were guesses, both were
  ; wrong once, so the ordering is stated rather than inferred (§3.61).
  ;
  ; The card exists so the box can be text-height: a single-line EDIT does not
  ; centre its text vertically.
  ${NSD_CreateText} 0 0 10u 10u "$INSTDIR"
  Pop $FolderText
  SetCtlColors $FolderText ${C_TEXT} ${C_SURFACE}
  System::Call 'uxtheme::SetWindowTheme(p $FolderText, w " ", w " ")'
  !insertmacro Font $FolderText $FontBody

  ; The sunken frame is an ex-style nsDialogs puts on every text box, not a
  ; theme, so SetWindowTheme cannot reach it.
  System::Call 'user32::GetWindowLongW(p $FolderText, i ${GWL_EXSTYLE}) i .r0'
  IntOp $1 ${WS_EX_CLIENTEDGE} | ${WS_EX_WINDOWEDGE}
  IntOp $1 $1 ~
  IntOp $0 $0 & $1
  System::Call 'user32::SetWindowLongW(p $FolderText, i ${GWL_EXSTYLE}, i r0)'
  IntOp $2 ${SWP_FRAMECHANGED} | ${SWP_NOMOVE}
  IntOp $2 $2 | ${SWP_NOSIZE}
  IntOp $2 $2 | ${SWP_NOZORDER}
  System::Call 'user32::SetWindowPos(p $FolderText, p 0, i 0, i 0, i 0, i 0, i r2)'
  SendMessage $FolderText ${EM_SETMARGINS} ${EC_BOTHMARGINS} 0x00040004
  !insertmacro Place $FolderText 296 306 272 18

  !insertmacro Fill $FolderCard 284 296 296 38 ${RADIUS} ${C_SURFACE}
  ${NSD_RemoveExStyle} $FolderCard ${WS_EX_TRANSPARENT}
  IntOp $0 ${SWP_NOMOVE} | ${SWP_NOSIZE}
  System::Call 'user32::SetWindowPos(p $FolderCard, p ${IXD_HWND_BOTTOM}, \
      i 0, i 0, i 0, i 0, i r0)'

  !insertmacro Pill $0 "Browse" 594 296 92 38 ${C_TEXT} ${C_SURFACE} OnBrowse
  !insertmacro Pill $0 "Cancel" 438 394 112 38 ${C_TEXT} ${C_SURFACE} GoCancel
  !insertmacro Pill $0 "Install" 560 394 132 38 ${C_WHITE} ${C_ACCENT} GoNext

  ; Show the mode MultiUser started in, rather than assuming "just me".
  ${If} $MultiUser.InstallMode == "AllUsers"
    Push 0
    Call MarkAllUsers
  ${EndIf}
  nsDialogs::Show
FunctionEnd

Function MarkAllUsers
  Pop $0
  SetCtlColors $CardAll ${C_TEXT} ${C_CARD}
  SetCtlColors $CardAllTitle ${C_TEXT} ${C_CARD}
  SetCtlColors $CardAllSub ${C_DIM} ${C_CARD}
  SetCtlColors $CardUser ${C_TEXT} ${C_SURFACE}
  SetCtlColors $CardUserTitle ${C_TEXT} ${C_SURFACE}
  SetCtlColors $CardUserSub ${C_DIM} ${C_SURFACE}
  SetCtlColors $CardAllDot ${C_ACCENT} ${C_ACCENT}
  SetCtlColors $CardUserDot ${C_FAINT} ${C_FAINT}
  Call RestateFolder
FunctionEnd

; Both handlers repaint everything belonging to a card. The labels sitting on a
; card carry their own background, and recolouring only the card left the words
; on the old colour — which reads as the panel shifting when the mode changes.
Function OnPickUser
  Pop $0
  Call MultiUser.InstallMode.CurrentUser
  SetCtlColors $CardUser ${C_TEXT} ${C_CARD}
  SetCtlColors $CardUserTitle ${C_TEXT} ${C_CARD}
  SetCtlColors $CardUserSub ${C_DIM} ${C_CARD}
  SetCtlColors $CardAll ${C_TEXT} ${C_SURFACE}
  SetCtlColors $CardAllTitle ${C_TEXT} ${C_SURFACE}
  SetCtlColors $CardAllSub ${C_DIM} ${C_SURFACE}
  SetCtlColors $CardUserDot ${C_ACCENT} ${C_ACCENT}
  SetCtlColors $CardAllDot ${C_FAINT} ${C_FAINT}
  ${NSD_SetText} $FolderText "$INSTDIR"
  Call RestateFolder
FunctionEnd

Function OnPickAll
  Pop $0
  Call MultiUser.InstallMode.AllUsers
  Push 0
  Call MarkAllUsers
  ${NSD_SetText} $FolderText "$INSTDIR"
FunctionEnd

; The folder box belongs to neither card and must not follow either of them.
; The caret is dropped as well: a box holding its selection after a click reads
; as a third colour nobody chose.
Function RestateFolder
  SetCtlColors $FolderCard ${C_SURFACE} ${C_SURFACE}
  SetCtlColors $FolderText ${C_TEXT} ${C_SURFACE}
  SendMessage $FolderText ${EM_SETSEL} 0 0
  System::Call 'user32::InvalidateRect(p $Dialog, p 0, i 1)'
FunctionEnd

Function OnBrowse
  Pop $0
  ${NSD_GetText} $FolderText $1
  nsDialogs::SelectFolderDialog "Where should it go?" "$1"
  Pop $2
  ${If} $2 != error
    ${NSD_SetText} $FolderText "$2"
  ${EndIf}
FunctionEnd

Function PageWhereLeave
  ; The box wins. The cards move it, and Browse moves it, but somebody who
  ; types a path means it — and the mode macros above rewrite $INSTDIR as a
  ; side effect, so this has to be the last word.
  ${NSD_GetText} $FolderText $0
  ${If} $0 != ""
    StrCpy $INSTDIR "$0"
  ${EndIf}
  StrCpy $Step 1
FunctionEnd

; ---------------------------------------------------------------------------
; Page two — ours, on the instfiles page's dialog
; ---------------------------------------------------------------------------
;
; **Nothing here is borrowed any more, and that is the point.** Three rounds of
; screenshots went into making Windows' own progress bar look right on a dark
; page: themed, it painted black with a single light chunk at the far end —
; the page's background erased its pixels and the control never repainted them
; — and un-themed, its colours come from PBM_SETBARCOLOR, which takes a
; COLORREF (0x00BBGGRR) rather than the RGB the rest of this file is written
; in, and it came out black anyway on a machine nothing here can run.
;
; So the bar is two STATIC controls: a groove and a fill. That is the same
; primitive every rectangle on pages one and three is made of — the ones the
; user approved — and it cannot be drawn wrong by a theme, because no theme is
; involved. Its width is moved by `Tick`, called from the install section
; between roughly equal shares of the payload's bytes, so the motion is real
; and not a guess. NSIS's own bar and its file list are hidden outright.
;
; The rest of the page is the brand panel and a card, raw-created for the same
; reason. The old page was the colours and nothing else, which is what a
; screenshot of a mostly-black rectangle with one word on it looks like.
Function PageInstallShow
  StrCpy $Step 1
  StrCpy $Ticks 0
  Call HideStockButtons
  Call HideParentChrome
  FindWindow $PageHwnd "#32770" "" $HWNDPARENT
  SetCtlColors $PageHwnd ${C_TEXT} ${C_BG}
  !insertmacro Place $PageHwnd 0 0 ${WIN_W} ${WIN_H}

  ; **Built out of sight, then shown.** Pages one and three are assembled while
  ; nsDialogs is still holding their dialog back, and every rounded corner on
  ; them comes out right. This page is already on screen when its show callback
  ; runs, so each control painted itself as a full rectangle before
  ; `SetWindowRgn` clipped it — and the corner pixels it had already put down
  ; stayed there, because taking a region away from a child does not repaint
  ; the parent underneath it. Measured on the user's screenshot: the card's
  ; corner was square to the pixel while the region call was demonstrably
  ; emitted.
  ShowWindow $PageHwnd ${SW_HIDE}

  ; **Every** child of this page, whatever its id, and then back come the ones
  ; we want. Hiding them by id was hiding three — the file list, the "show
  ; details" button and the bar — and missing a fourth: a grey rule at
  ; (11, 220), 290 px wide, measured off the user's screenshot at 0xA0A0A0.
  ; That is NSIS's own template geometry, and no id in this script accounted
  ; for it. Walking the children needs to know nothing.
  System::Call 'user32::GetWindow(p $PageHwnd, i ${GW_CHILD}) p .r1'
  ${Do}
    ${If} $1 == 0
      ${ExitDo}
    ${EndIf}
    ShowWindow $1 ${SW_HIDE}
    System::Call 'user32::GetWindow(p $1, i ${GW_HWNDNEXT}) p .r1'
  ${Loop}

  ; A backdrop of our own across the whole page. The dialog's background brush
  ; already paints it, but a control that owns the pixels is what stops the
  ; previous page's leftovers showing down the left edge — reported twice, and
  ; the second time after the page was already being placed at 0,0.
  !insertmacro RawFill $0 0 0 ${WIN_W} ${WIN_H} ${C_BG}
  !insertmacro ToBottom $0
  !insertmacro RawFill $0 0 0 ${PANEL_W} ${WIN_H} ${C_PANEL}
  !insertmacro ToBottom $0

  ; The panel, the same one as pages one and three. `BrandPanel` cannot be
  ; called here — every control in it is an ${NSD_Create*} — so it is the same
  ; layout through the raw macros.
  !insertmacro RawPicture $0 "mark.bmp" 28 34 40 40

  !insertmacro RawLabel $0 "Internet Xtreme" 28 84 200 26 $FontH1 ${C_TEXT} ${C_PANEL}
  !insertmacro RawLabel $0 "Downloader" 28 110 200 26 $FontH1 ${C_TEXT} ${C_PANEL}
  !insertmacro RawLabel $0 "Version @VERSION@" 28 144 200 18 $FontSmall ${C_FAINT} ${C_PANEL}

  ; Step one is behind us, step two is this page, step three is not yet. The
  ; dots are pictures — each is a circle on the panel's colour, and the panel
  ; is the only thing behind them, so the blend is known at build time.
  !insertmacro RawPicture $0 "dot-good.bmp" 28 204 11 11
  !insertmacro RawLabel $0 "Where it goes" 52 200 180 20 $FontBody ${C_DIM} ${C_PANEL}

  !insertmacro RawPicture $0 "dot-accent.bmp" 28 248 11 11
  !insertmacro RawLabel $0 "Installing" 52 244 180 20 $FontButton ${C_TEXT} ${C_PANEL}

  !insertmacro RawPicture $0 "dot-faint.bmp" 28 292 11 11
  !insertmacro RawLabel $0 "Ready" 52 288 180 20 $FontBody ${C_FAINT} ${C_PANEL}

  !insertmacro RawLabel $0 "No ffmpeg. No yt-dlp. No telemetry." \
      28 420 210 16 $FontSmall ${C_FAINT} ${C_PANEL}

  ; The content side.
  !insertmacro RawLabel $0 "Installing" 284 44 380 30 $FontH1 ${C_TEXT} ${C_BG}
  !insertmacro RawLabel $0 "About half a minute. Nothing else is asked of you." \
      284 78 380 20 $FontBody ${C_DIM} ${C_BG}

  ; The card, drawn rounded at build time on the background it sits on.
  !insertmacro RawPicture $0 "card.bmp" 284 130 402 110
  !insertmacro RawLabel $0 "Copying files" 302 150 366 20 $FontButton ${C_TEXT} ${C_SURFACE}

  ; The bar: groove, then fill, then the fill lifted above it by name. Both are
  ; square — a rounded fill needs a fresh region on every step, and a radius on
  ; a four-pixel-wide window is a shape nobody can predict from here.
  !insertmacro RawFill $0 302 188 366 8 ${C_BG}
  !insertmacro RoundCorners $0 366 8 8
  !insertmacro RawFill $BarFill 302 188 0 8 ${C_ACCENT}
  !insertmacro ToTop $BarFill

  ; NSIS's own "Extract: …" line, kept, moved onto the card and recoloured.
  ; It is the one part of this page worth borrowing: it says what is being
  ; written, and it is already correct.
  GetDlgItem $1 $PageHwnd 1006
  ShowWindow $1 ${SW_SHOW}
  SetCtlColors $1 ${C_DIM} ${C_SURFACE}
  !insertmacro Font $1 $FontSmall
  !insertmacro Place $1 302 208 366 18
  !insertmacro ToTop $1

  ; Now show it, and repaint the lot — background first, then every child on
  ; top of it. `RDW_ALLCHILDREN` is the part that matters: without it the
  ; erase stops at the dialog and the controls keep whatever they had.
  ShowWindow $PageHwnd ${SW_SHOW}
  System::Call 'user32::RedrawWindow(p $PageHwnd, p 0, p 0, i ${RDW_WHOLE})'
FunctionEnd

; The bar advances by one share of the payload's bytes. `${TICKS}` is written
; by packaging/installer_custom.py from the payload it is packing, and the
; `Call Tick`s are interleaved with the File instructions so that each one
; stands for about the same number of bytes — which makes this bar a truer
; report of the wait than the one it replaced, since NSIS's counts
; instructions and a hundred-megabyte Qt library is one instruction.
Function Tick
  ; The registers are the install section's; it is mid-instruction when this
  ; runs.
  Push $0
  Push $1
  IntOp $Ticks $Ticks + 1
  IntOp $0 $Ticks * 366
  IntOp $0 $0 / ${TICKS}
  ${If} $0 > 366
    StrCpy $0 366
  ${EndIf}
  ; Sized **and** raised on every step, in one call. The fill is created after
  ; the groove and lifted above it once in `PageInstallShow`, and it still did
  ; not appear — the screenshot has the groove's colour across the whole bar
  ; and the accent nowhere. Whether that was the z-order or the resize, this
  ; asserts both, and it costs one call a second.
  ;
  ; Its own position, not the origin: a child is placed against its parent, so
  ; passing 0,0 would put the bar in the corner of the window.
  System::Call 'user32::SetWindowPos(p $BarFill, p ${IXD_HWND_TOP}, \
      i 302, i 188, i $0, i 8, i ${SWP_BARSTEP})'
  ; Rounded to match the groove it sits in, at whatever width it has reached.
  ; The region has to be made afresh each step — `RoundCorners` takes its size
  ; at compile time and this one is only known here. `SetWindowRgn` takes
  ; ownership of the region, so there is nothing to free.
  System::Call 'gdi32::CreateRoundRectRgn(i 0, i 0, i $0, i 8, i 8, i 8) p .s'
  Pop $1
  System::Call 'user32::SetWindowRgn(p $BarFill, p $1, i 1)'

  ; **Painted now, and only this window.** What was here was `InvalidateRect`
  ; on the fill, which only marks it: the paint happens whenever the dialog's
  ; thread next gets to it, and this function runs on the install thread,
  ; which returns straight into a `File` extracting a hundred megabytes.
  ;
  ; Measured on the user's screenshot (l1.png, §3.74): a 15 px band of the
  ; groove's colour sat inside the fill, near its right end. Its left edge
  ; traced a radius-4 cap peaking at x=639 and its right edge one peaking at
  ; x=653 — the fill at tick 22 and at tick 23, so the band was exactly `new
  ; region − old region`, the strip that step had just gained, never painted.
  ; 366/24 is 15.25 px: one tick wide, to the pixel.
  ;
  ; `RDW_UPDATENOW` is the whole of the fix — the window paints before this
  ; returns instead of being left marked. It is asked of the **fill alone**:
  ; the gained strip is inside the fill's own rectangle, so nothing else needs
  ; to draw, and the first version of this asked the page with
  ; `RDW_ALLCHILDREN`, which would have brought the full-page backdrop into
  ; every one of the twenty-four steps (§3.75). The groove never needs
  ; repainting because the bar only ever grows.
  System::Call 'user32::RedrawWindow(p $BarFill, p 0, p 0, i ${RDW_NOW})'
  Pop $1
  Pop $0
FunctionEnd

; ---------------------------------------------------------------------------
; Page three — done
; ---------------------------------------------------------------------------
Function PageDone
  StrCpy $Step 2
  nsDialogs::Create 1018
  Pop $Dialog
  SetCtlColors $Dialog ${C_TEXT} ${C_BG}
  Call HideStockButtons
  Call HideParentChrome
  Call BrandPanel

  ${NSD_CreateBitmap} 0 0 10u 10u ""
  Pop $0
  ${NSD_SetImage} $0 "$PLUGINSDIR\tick.bmp" $1
  !insertmacro Place $0 284 44 36 36

  !insertmacro Label $0 "Installed" 334 44 340 30 $FontH1 ${C_TEXT} ${C_BG}
  !insertmacro Label $0 "One step left, and it is in the browser." \
      334 78 340 20 $FontBody ${C_DIM} ${C_BG}

  !insertmacro Fill $0 284 130 402 96 ${RADIUS} ${C_SURFACE}
  !insertmacro Label $0 "Load the extension" 302 144 370 20 $FontButton ${C_TEXT} ${C_SURFACE}
  !insertmacro Label $0 "Open chrome://extensions, turn on Developer mode and load$\r$\nthe folder beside the application. The app shows the exact path." \
      302 168 370 40 $FontSmall ${C_DIM} ${C_SURFACE}

  ; A drawn tick box: a real check box is a BUTTON, and a BUTTON paints its own
  ; face — the same reason the Browse button came out white.
  !insertmacro Fill $StartBox 284 246 18 18 6 ${C_ACCENT}
  ${NSD_OnClick} $StartBox OnToggleStart
  !insertmacro Label $0 "Start @APP_NAME@ now" 312 245 360 20 $FontBody ${C_TEXT} ${C_BG}
  ${NSD_OnClick} $0 OnToggleStart

  !insertmacro Pill $0 "Finish" 560 394 132 38 ${C_WHITE} ${C_ACCENT} GoNext
  nsDialogs::Show
FunctionEnd

Function OnToggleStart
  Pop $0
  ${If} $StartNow == 1
    StrCpy $StartNow 0
    SetCtlColors $StartBox ${C_FAINT} ${C_SURFACE}
  ${Else}
    StrCpy $StartNow 1
    SetCtlColors $StartBox ${C_ACCENT} ${C_ACCENT}
  ${EndIf}
  System::Call 'user32::InvalidateRect(p $Dialog, p 0, i 1)'
FunctionEnd

Function PageDoneLeave
  ; Launched through Explorer, so it does not inherit this installer's
  ; elevation: a child of an elevated process is elevated too, and a download
  ; manager running as administrator for the rest of the session is not what
  ; installing should cost. Explorer runs as the logged-in user.
  ${If} $StartNow == 1
    Exec '"$WINDIR\explorer.exe" "$INSTDIR\@LAUNCHER@"'
  ${EndIf}
FunctionEnd

Page custom PageWhere PageWhereLeave
Page instfiles "" PageInstallShow
Page custom PageDone PageDoneLeave

Section "Install"
  ; Close a copy that is already running, before a single file is written.
  ; The application does quit when it starts an update, but that is a race and
  ; NSIS got to the first locked file first (§437).
  DetailPrint "Closing @APP_NAME@ if it is running…"
  ExecWait 'taskkill /IM "@LAUNCHER@"'
  Sleep 2500
  ExecWait 'taskkill /IM "@LAUNCHER@" /F'
  Sleep 800

  ; The payload, one `File` at a time, with `Call Tick` between roughly equal
  ; shares of its bytes. `File /r` was one instruction and told the bar
  ; nothing; this is written by packaging/installer_custom.py from the folder
  ; it is packing. It is also why `\*` versus `\*.*` no longer matters — the
  ; list is taken from the filesystem here rather than matched over there.
@COPY_BODY@

  CreateDirectory "$SMPROGRAMS\@APP_NAME@"
  CreateShortCut "$SMPROGRAMS\@APP_NAME@\@APP_NAME@.lnk" "$INSTDIR\@LAUNCHER@"
  CreateShortCut "$SMPROGRAMS\@APP_NAME@\Uninstall @APP_NAME@.lnk" "$INSTDIR\uninstall.exe"
  CreateShortCut "$DESKTOP\@APP_NAME@.lnk" "$INSTDIR\@LAUNCHER@"

  ; SHCTX is HKLM for an all-users install and HKCU for a per-user one.
  ; MultiUser sets it; writing the literal hive is the mistake it exists to
  ; prevent.
  WriteRegStr SHCTX "Software\@APP_SLUG@" "InstallDir" "$INSTDIR"
  WriteRegStr SHCTX "Software\@APP_SLUG@" "InstallMode" "$MultiUser.InstallMode"
  WriteRegStr SHCTX "@UNINSTALL_KEY@" "DisplayName" "@APP_NAME@"
  WriteRegStr SHCTX "@UNINSTALL_KEY@" "DisplayVersion" "@VERSION@"
  WriteRegStr SHCTX "@UNINSTALL_KEY@" "Publisher" "@PUBLISHER@"
  WriteRegStr SHCTX "@UNINSTALL_KEY@" "DisplayIcon" "$INSTDIR\@LAUNCHER@"
  WriteRegStr SHCTX "@UNINSTALL_KEY@" "UninstallString" "$INSTDIR\uninstall.exe"
  WriteRegStr SHCTX "@UNINSTALL_KEY@" "InstallLocation" "$INSTDIR"
  WriteRegDWORD SHCTX "@UNINSTALL_KEY@" "NoModify" 1
  WriteRegDWORD SHCTX "@UNINSTALL_KEY@" "NoRepair" 1
  WriteUninstaller "$INSTDIR\uninstall.exe"

  ; An in-app update runs this silently, and a silent run has no page three to
  ; press Finish on — so it reopens the application itself, through Explorer
  ; for the same elevation reason as above.
  ${If} ${Silent}
    Exec '"$WINDIR\explorer.exe" "$INSTDIR\@LAUNCHER@"'
  ${EndIf}

SectionEnd

Section "Uninstall"
  ExecWait 'taskkill /IM "@LAUNCHER@" /F'
  Sleep 500
  Delete "$DESKTOP\@APP_NAME@.lnk"
  Delete "$SMPROGRAMS\@APP_NAME@\@APP_NAME@.lnk"
  Delete "$SMPROGRAMS\@APP_NAME@\Uninstall @APP_NAME@.lnk"
  RMDir "$SMPROGRAMS\@APP_NAME@"
  ; Takes the generated extension folders with it. They are written by the
  ; application rather than by this installer, so nothing else would.
  RMDir /r "$INSTDIR"
  DeleteRegKey SHCTX "@UNINSTALL_KEY@"
  DeleteRegKey SHCTX "Software\@APP_SLUG@"
SectionEnd
"""


#: How many steps the progress bar takes. Twenty-four is a step every four per
#: cent, which on a twenty-second install is a move about every second — often
#: enough to look alive, few enough that each `Call Tick` is worth its place in
#: the script.
TICKS = 24


def copy_body(payload: Path, ticks: int = TICKS, indent: str = "  ") -> str:
    """`SetOutPath`/`File` for every file in *payload*, with the bar's steps.

    The bytes are what the steps are spaced by, not the file count: a payload
    that is two thirds one Qt library and one third three hundred small files
    would otherwise sit still for most of the install and then finish in a
    rush. Each tick stands for about `1/ticks` of the total size.
    """
    def literal(text: str) -> str:
        """`$` is NSIS's variable sigil; a literal one is written `$$`."""
        return text.replace("$", "$$")

    files = sorted(
        (item for item in payload.rglob("*") if item.is_file()),
        key=lambda item: (item.parent.as_posix(), item.name),
    )
    total = sum(item.stat().st_size for item in files) or 1
    lines: list[str] = []
    here = None
    written = 0
    emitted = 0
    for item in files:
        relative = item.parent.relative_to(payload)
        target = "$INSTDIR" if relative == Path(".") else (
            "$INSTDIR\\" + literal(str(relative).replace("/", "\\")))
        if target != here:
            lines.append(f'{indent}SetOutPath "{target}"')
            here = target
        lines.append(f'{indent}File "{literal(item.as_posix())}"')
        written += item.stat().st_size
        while emitted < ticks and written * ticks >= total * (emitted + 1):
            lines.append(f"{indent}Call Tick")
            emitted += 1
    # Whatever rounding left over, so the bar always finishes full.
    for _ in range(ticks - emitted):
        lines.append(f"{indent}Call Tick")
    return "\n".join(lines)


def script(*, app_name: str, app_slug: str, version: str, publisher: str,
           output: str, payload: str, launcher: str, icon: str, art: str,
           uninstall_key: str, ticks: int = TICKS) -> str:
    """The custom installer's NSIS source, with every placeholder filled in."""
    values = {
        "@APP_NAME@": app_name,
        "@APP_SLUG@": app_slug,
        "@VERSION@": version,
        "@PUBLISHER@": publisher,
        "@OUTPUT@": output,
        "@PAYLOAD@": payload,
        "@LAUNCHER@": launcher,
        "@ICON@": icon,
        "@ART@": art,
        "@UNINSTALL_KEY@": uninstall_key,
        "@TICKS@": str(ticks),
        # Last, because it is the only value that itself contains a path with
        # no placeholders left to confuse — and the biggest by far.
        "@COPY_BODY@": copy_body(Path(payload), ticks),
    }
    text = _SCRIPT
    for token, value in values.items():
        text = text.replace(token, value)
    return text
