"""The custom-window Windows installer.

The same job as the MUI2 script in `build.py` — files, shortcuts, registry,
uninstaller — behind the window the user approved after four rounds of the
preview (`installer-preview.nsi`, context.md §3.58 and §3.61).

**It is published beside the MUI2 installer, not instead of it.** The user's
instruction: *"you can make that custom installer too but before push it for
later release instead of old installer let me test it then when i told you you
can replace the old one with the custom one."* So it is an extra asset called
`…-windows-x64-custom-installer.exe`, and the name deliberately avoids the word
*setup*: `Release.asset()` returns the first published file whose name contains
every piece it was given, and an updating build asks for
`("windows", "setup", ".exe")`. A custom installer that matched that could be
handed to a machine as its update, which is not something to leave to the order
GitHub happens to list assets in.

Placeholders are `@NAME@` and substituted with `str.replace`, not `str.format`.
An NSIS script is mostly `${...}`, and a format string would need every one of
them doubled — which is a transcription error waiting to happen in a file that
cannot be run here.

What differs from the preview, which installed nothing:

* **MultiUser drives the mode**, so "everyone" elevates and writes to HKLM and
  "just me" does not. The cards set it; the folder box still wins, because
  somebody who types a path means it.
* **Page two is the real `instfiles` page**, restyled. Controls cannot be added
  to it through nsDialogs (§3.61), so it has the colours, the accent progress
  bar and the panel's colour block down the left, but not the step list. It is
  on screen for about twenty seconds.
* **The install section is the MUI2 one**, including closing a running copy
  before writing (§437) and reopening the application through Explorer after a
  silent update (§458).
"""

from __future__ import annotations

_SCRIPT = r"""
; Generated by packaging/installer_custom.py — do not edit in dist/.
Unicode true

!include "nsDialogs.nsh"
!include "LogicLib.nsh"
!include "WinMessages.nsh"
!include "FileFunc.nsh"

!define MULTIUSER_EXECUTIONLEVEL Highest
!define MULTIUSER_INSTALLMODE_COMMANDLINE
!define MULTIUSER_INSTALLMODE_INSTDIR "@APP_SLUG@"
!define MULTIUSER_INSTALLMODE_INSTALL_REGISTRY_KEY "Software\@APP_SLUG@"
!define MULTIUSER_INSTALLMODE_INSTALL_REGISTRY_VALUENAME "InstallDir"
!define MULTIUSER_INSTALLMODE_DEFAULT_REGISTRY_KEY "Software\@APP_SLUG@"
!define MULTIUSER_INSTALLMODE_DEFAULT_REGISTRY_VALUENAME "InstallDir"
!define MULTIUSER_INSTALLMODE_FUNCTION OnInstallModeChanged
!include "MultiUser.nsh"

Name "@APP_NAME@"
OutFile "@OUTPUT@"
Caption "@APP_NAME@"
BrandingText " "
Icon "@ICON@"
XPStyle on
ShowInstDetails show

!define WIN_W 720
!define WIN_H 460
!define PANEL_W 250

; Straight out of ixd/ui/theme.py, so the installer and the application are the
; same object rather than two things that resemble each other.
!define C_BG      0x0D0F16
!define C_PANEL   0x0A0C12
!define C_SURFACE 0x141827
!define C_CARD    0x181D2F
!define C_TEXT    0xE7ECFF
!define C_DIM     0x95A0C2
!define C_FAINT   0x6B7597
!define C_ACCENT  0x5B8CFF
!define C_GOOD    0x43D6A0
!define C_WHITE   0xFFFFFF

!ifndef GWL_STYLE
  !define GWL_STYLE -16
!endif
!ifndef GWL_EXSTYLE
  !define GWL_EXSTYLE -20
!endif
!ifndef WS_EX_WINDOWEDGE
  !define WS_EX_WINDOWEDGE 0x00000100
!endif
!ifndef WS_EX_CLIENTEDGE
  !define WS_EX_CLIENTEDGE 0x00000200
!endif
!define WS_CHROME        0x00CF0000
!define SWP_FRAMECHANGED 0x0020
!define SWP_NOZORDER     0x0004
!define SWP_NOMOVE       0x0002
!define SWP_NOSIZE       0x0001
!define IXD_HWND_BOTTOM  1
!ifndef SM_CXSCREEN
  !define SM_CXSCREEN 0
!endif
!ifndef SM_CYSCREEN
  !define SM_CYSCREEN 1
!endif
; SS_CENTER|SS_CENTERIMAGE, precomputed: ${NSD_AddStyle} hands its argument to
; System::Int64Op, which takes a number and not an expression.
!define SS_BUTTONTEXT 0x00000201
!define EC_BOTHMARGINS 0x0003

; SC_MOVE (0xF010) with HTCAPTION (2). Sent to a window, it puts Windows into
; its own move loop — the way dragging a title bar does, except that it can be
; started from anywhere.
;
; This is what makes a borderless window movable **without a plugin**. The
; header of this file used to say it could not be done: answering WM_NCHITTEST
; needs a window procedure, and NSIS has no way to subclass a window. True, and
; beside the point — Windows will move a window on request, and asking is a
; `SendMessage`. Reported as "the window is not moveable when i try to move it
; from center of the screen", which is a fair thing to expect of a window.
;
; One honest difference from a title bar: a label reports its click on button
; *up* (STN_CLICKED), so the move loop begins after the button is released.
; The window then follows the mouse until the next click puts it down, rather
; than being dragged with the button held.
!define SC_DRAGMOVE 0xF012

Var Dialog
Var FontH1
Var FontBody
Var FontSmall
Var FontButton
Var CardUser
Var CardAll
Var CardUserDot
Var CardAllDot
Var CardUserTitle
Var CardUserSub
Var CardAllTitle
Var CardAllSub
Var FolderCard
Var FolderText
Var Step
Var Tmp
Var StartNow
Var StartBox

!macro RoundCorners hwnd w h radius
  System::Call 'gdi32::CreateRoundRectRgn(i 0, i 0, i ${w}, i ${h}, i ${radius}, i ${radius}) p .s'
  Pop $Tmp
  System::Call 'user32::SetWindowRgn(p ${hwnd}, p $Tmp, i 1)'
!macroend

!macro Place hwnd x y w h
  System::Call 'user32::MoveWindow(p ${hwnd}, i ${x}, i ${y}, i ${w}, i ${h}, i 1)'
!macroend

!macro Font hwnd font
  SendMessage ${hwnd} ${WM_SETFONT} ${font} 1
!macroend

!macro Label var text x y w h font fg bg
  ${NSD_CreateLabel} 0 0 10u 10u "${text}"
  Pop ${var}
  SetCtlColors ${var} ${fg} ${bg}
  !insertmacro Font ${var} ${font}
  !insertmacro Place ${var} ${x} ${y} ${w} ${h}
!macroend

!macro Fill var x y w h radius colour
  ${NSD_CreateLabel} 0 0 10u 10u ""
  Pop ${var}
  SetCtlColors ${var} ${colour} ${colour}
  !insertmacro Place ${var} ${x} ${y} ${w} ${h}
  !insertmacro RoundCorners ${var} ${w} ${h} ${radius}
!macroend

; Every button here is a label. SetCtlColors answers WM_CTLCOLOR*, and a real
; push button ignores the brush it is handed and paints its own face — the
; Browse button asked for the dark surface and Windows drew it stock white
; (context.md §3.58). nsDialogs gives every label SS_NOTIFY, so it reports its
; own clicks and needs nothing else.
!macro Pill var text x y w h fg bg onclick
  ${NSD_CreateLabel} 0 0 10u 10u "${text}"
  Pop ${var}
  ${NSD_AddStyle} ${var} ${SS_BUTTONTEXT}
  SetCtlColors ${var} ${fg} ${bg}
  !insertmacro Font ${var} $FontButton
  !insertmacro Place ${var} ${x} ${y} ${w} ${h}
  !insertmacro RoundCorners ${var} ${w} ${h} 9
  ${NSD_OnClick} ${var} ${onclick}
!macroend

Function OnInstallModeChanged
  ; A remembered installation wins. MultiUser calls this whenever the mode is
  ; set, including from MULTIUSER_INIT — which runs after it has read the
  ; previous InstallDir out of the registry. Overwriting $INSTDIR here threw
  ; that away, so an upgrade never targeted the folder the user installed into
  ; (session-log §455). SHCTX follows the mode, so this reads the hive the
  ; Install section wrote to.
  ClearErrors
  ReadRegStr $0 SHCTX "Software\@APP_SLUG@" "InstallDir"
  ${IfNot} ${Errors}
  ${AndIf} $0 != ""
    StrCpy $INSTDIR "$0"
    Return
  ${EndIf}
  ${If} $MultiUser.InstallMode == "AllUsers"
    StrCpy $INSTDIR "$PROGRAMFILES64\@APP_SLUG@"
  ${Else}
    StrCpy $INSTDIR "$APPDATA\@APP_SLUG@"
  ${EndIf}
FunctionEnd

Function .onInit
  !insertmacro MULTIUSER_INIT
  InitPluginsDir
  File /oname=$PLUGINSDIR\mark.bmp "@ART@\mark.bmp"
  File /oname=$PLUGINSDIR\tick.bmp "@ART@\tick.bmp"
FunctionEnd

Function un.onInit
  !insertmacro MULTIUSER_UNINIT
FunctionEnd

Function .onGUIInit
  ; Strip the title bar and the resize frame, then size and centre what is
  ; left. NSIS gives no way to ask for a window like this.
  System::Call 'user32::GetWindowLongW(p $HWNDPARENT, i ${GWL_STYLE}) i .r0'
  IntOp $1 ${WS_CHROME} ~
  IntOp $0 $0 & $1
  System::Call 'user32::SetWindowLongW(p $HWNDPARENT, i ${GWL_STYLE}, i r0)'

  System::Call 'user32::GetSystemMetrics(i ${SM_CXSCREEN}) i .r2'
  System::Call 'user32::GetSystemMetrics(i ${SM_CYSCREEN}) i .r3'
  IntOp $2 $2 - ${WIN_W}
  IntOp $2 $2 / 2
  IntOp $3 $3 - ${WIN_H}
  IntOp $3 $3 / 2
  IntOp $4 ${SWP_FRAMECHANGED} | ${SWP_NOZORDER}
  System::Call 'user32::SetWindowPos(p $HWNDPARENT, p 0, i r2, i r3, \
      i ${WIN_W}, i ${WIN_H}, i r4)'
  !insertmacro RoundCorners $HWNDPARENT ${WIN_W} ${WIN_H} 14

  ; The panel's colour, not the page's. The instfiles page cannot take controls
  ; of ours (§3.61), so it is inset to the content area instead and this shows
  ; through on its left — the colour block is continuous across all three pages
  ; even though the step list is only on the two that are ours.
  SetCtlColors $HWNDPARENT ${C_TEXT} ${C_PANEL}

  GetDlgItem $0 $HWNDPARENT 1018
  !insertmacro Place $0 0 0 ${WIN_W} ${WIN_H}
  GetDlgItem $0 $HWNDPARENT 1028
  ShowWindow $0 ${SW_HIDE}
  GetDlgItem $0 $HWNDPARENT 1256
  ShowWindow $0 ${SW_HIDE}

  CreateFont $FontH1     "Segoe UI" 15 600
  CreateFont $FontBody   "Segoe UI" 10 400
  CreateFont $FontSmall  "Segoe UI" 9  400
  CreateFont $FontButton "Segoe UI" 10 600

  Call HideStockButtons
  StrCpy $Step 0
  StrCpy $StartNow 1
FunctionEnd

; NSIS's three buttons are never shown. They cannot take our colours, and they
; sit under a page dialog that covers the window; the pills post WM_COMMAND to
; the parent instead, which is what clicking them would have sent.
Function HideStockButtons
  GetDlgItem $0 $HWNDPARENT 1
  ShowWindow $0 ${SW_HIDE}
  GetDlgItem $0 $HWNDPARENT 2
  ShowWindow $0 ${SW_HIDE}
  GetDlgItem $0 $HWNDPARENT 3
  ShowWindow $0 ${SW_HIDE}
FunctionEnd

Function GoNext
  Pop $0
  SendMessage $HWNDPARENT ${WM_COMMAND} 1 0
FunctionEnd

Function GoCancel
  Pop $0
  SendMessage $HWNDPARENT ${WM_COMMAND} 2 0
FunctionEnd

Function OnClose
  Pop $0
  SendMessage $HWNDPARENT ${WM_CLOSE} 0 0
FunctionEnd

; Grab anywhere on the panel or the strip above the content and the window
; moves. Both are the parts with nothing else to click on, which is exactly
; where somebody reaches for a window that has no title bar.
Function DragWindow
  Pop $0
  SendMessage $HWNDPARENT ${WM_SYSCOMMAND} ${SC_DRAGMOVE} 0
FunctionEnd

Function BrandPanel
  !insertmacro Fill $0 0 0 ${PANEL_W} ${WIN_H} 0 ${C_PANEL}
  ${NSD_OnClick} $0 DragWindow

  ; A grab strip across the top of the content side, where a title bar would
  ; be. Transparent to look at — it carries the background colour — and it is
  ; created before everything else on this page so nothing it would cover has
  ; been made yet.
  ${NSD_CreateLabel} 0 0 10u 10u ""
  Pop $0
  SetCtlColors $0 ${C_BG} ${C_BG}
  !insertmacro Place $0 ${PANEL_W} 0 470 34
  ${NSD_OnClick} $0 DragWindow

  ${NSD_CreateBitmap} 0 0 10u 10u ""
  Pop $0
  ${NSD_SetImage} $0 "$PLUGINSDIR\mark.bmp" $1
  !insertmacro Place $0 28 34 40 40

  ; 26px boxes, 26px apart: at 15pt Segoe UI a 20px box cut the letters through
  ; their descenders and the two lines collided.
  !insertmacro Label $1 "Internet Xtreme" 28 84 200 26 $FontH1 ${C_TEXT} ${C_PANEL}
  !insertmacro Label $1 "Downloader" 28 110 200 26 $FontH1 ${C_TEXT} ${C_PANEL}
  !insertmacro Label $1 "Version @VERSION@" 28 144 200 18 $FontSmall ${C_FAINT} ${C_PANEL}

  StrCpy $2 0
  StrCpy $3 200
  ${Do}
    ${If} $2 == 0
      StrCpy $4 "Where it goes"
    ${ElseIf} $2 == 1
      StrCpy $4 "Installing"
    ${Else}
      StrCpy $4 "Ready"
    ${EndIf}

    ; Every colour is a literal. SetCtlColors reads its arguments at compile
    ; time, so `SetCtlColors $6 $5 $5` compiles and paints black.
    ${NSD_CreateLabel} 0 0 10u 10u ""
    Pop $6
    ${If} $2 < $Step
      SetCtlColors $6 ${C_GOOD} ${C_GOOD}
    ${ElseIf} $2 == $Step
      SetCtlColors $6 ${C_ACCENT} ${C_ACCENT}
    ${Else}
      SetCtlColors $6 ${C_FAINT} ${C_FAINT}
    ${EndIf}
    IntOp $7 $3 + 4
    !insertmacro Place $6 28 $7 11 11
    !insertmacro RoundCorners $6 11 11 11

    ${NSD_CreateLabel} 0 0 10u 10u "$4"
    Pop $6
    ${If} $2 == $Step
      SetCtlColors $6 ${C_TEXT} ${C_PANEL}
      StrCpy $8 $FontButton
    ${ElseIf} $2 < $Step
      SetCtlColors $6 ${C_DIM} ${C_PANEL}
      StrCpy $8 $FontBody
    ${Else}
      SetCtlColors $6 ${C_FAINT} ${C_PANEL}
      StrCpy $8 $FontBody
    ${EndIf}
    !insertmacro Font $6 $8
    !insertmacro Place $6 52 $3 180 20

    IntOp $3 $3 + 44
    IntOp $2 $2 + 1
  ${LoopUntil} $2 >= 3

  !insertmacro Label $1 "No ffmpeg. No yt-dlp. No telemetry." \
      28 420 210 16 $FontSmall ${C_FAINT} ${C_PANEL}

  ; No `$` in front of the glyph: NSIS reads `$x` as a variable and drops it.
  ${NSD_CreateLabel} 0 0 10u 10u "✕"
  Pop $0
  ${NSD_AddStyle} $0 ${SS_BUTTONTEXT}
  SetCtlColors $0 ${C_DIM} ${C_BG}
  !insertmacro Font $0 $FontBody
  !insertmacro Place $0 664 16 28 28
  ${NSD_OnClick} $0 OnClose
FunctionEnd

; ---------------------------------------------------------------------------
; Page one — where it goes
; ---------------------------------------------------------------------------
Function PageWhere
  StrCpy $Step 0
  nsDialogs::Create 1018
  Pop $Dialog
  SetCtlColors $Dialog ${C_TEXT} ${C_BG}
  Call HideStockButtons
  Call BrandPanel

  !insertmacro Label $0 "Where should it go?" 284 44 380 30 $FontH1 ${C_TEXT} ${C_BG}
  !insertmacro Label $0 "Two answers, and they are not the same choice." \
      284 78 380 20 $FontBody ${C_DIM} ${C_BG}

  !insertmacro Fill $CardUser 284 118 402 62 11 ${C_CARD}
  ${NSD_OnClick} $CardUser OnPickUser
  !insertmacro Fill $CardUserDot 306 141 16 16 16 ${C_ACCENT}
  !insertmacro Label $CardUserTitle "Just me" 332 130 340 20 $FontButton ${C_TEXT} ${C_CARD}
  ${NSD_OnClick} $CardUserTitle OnPickUser
  !insertmacro Label $CardUserSub "No administrator needed  ·  %APPDATA%\@APP_SLUG@" \
      332 151 340 18 $FontSmall ${C_DIM} ${C_CARD}
  ${NSD_OnClick} $CardUserSub OnPickUser

  !insertmacro Fill $CardAll 284 190 402 62 11 ${C_SURFACE}
  ${NSD_OnClick} $CardAll OnPickAll
  !insertmacro Fill $CardAllDot 306 213 16 16 16 ${C_FAINT}
  !insertmacro Label $CardAllTitle "Everyone on this PC" 332 202 340 20 $FontButton ${C_TEXT} ${C_SURFACE}
  ${NSD_OnClick} $CardAllTitle OnPickAll
  !insertmacro Label $CardAllSub "Needs administrator  ·  Program Files" \
      332 223 340 18 $FontSmall ${C_DIM} ${C_SURFACE}
  ${NSD_OnClick} $CardAllSub OnPickAll

  !insertmacro Label $0 "FOLDER" 284 274 200 16 $FontSmall ${C_DIM} ${C_BG}

  ; The box first, its card afterwards, and the card pushed to the bottom of
  ; the z-order explicitly. A label carries WS_EX_TRANSPARENT and paints after
  ; the windows beneath it; stripping that is not enough either, because the
  ; earlier-created control is the one on top. Both were guesses, both were
  ; wrong once, so the ordering is stated rather than inferred (§3.61).
  ;
  ; The card exists so the box can be text-height: a single-line EDIT does not
  ; centre its text vertically.
  ${NSD_CreateText} 0 0 10u 10u "$INSTDIR"
  Pop $FolderText
  SetCtlColors $FolderText ${C_TEXT} ${C_SURFACE}
  System::Call 'uxtheme::SetWindowTheme(p $FolderText, w " ", w " ")'
  !insertmacro Font $FolderText $FontBody

  ; The sunken frame is an ex-style nsDialogs puts on every text box, not a
  ; theme, so SetWindowTheme cannot reach it.
  System::Call 'user32::GetWindowLongW(p $FolderText, i ${GWL_EXSTYLE}) i .r0'
  IntOp $1 ${WS_EX_CLIENTEDGE} | ${WS_EX_WINDOWEDGE}
  IntOp $1 $1 ~
  IntOp $0 $0 & $1
  System::Call 'user32::SetWindowLongW(p $FolderText, i ${GWL_EXSTYLE}, i r0)'
  IntOp $2 ${SWP_FRAMECHANGED} | ${SWP_NOMOVE}
  IntOp $2 $2 | ${SWP_NOSIZE}
  IntOp $2 $2 | ${SWP_NOZORDER}
  System::Call 'user32::SetWindowPos(p $FolderText, p 0, i 0, i 0, i 0, i 0, i r2)'
  SendMessage $FolderText ${EM_SETMARGINS} ${EC_BOTHMARGINS} 0x00040004
  !insertmacro Place $FolderText 296 306 272 18

  !insertmacro Fill $FolderCard 284 296 296 38 9 ${C_SURFACE}
  ${NSD_RemoveExStyle} $FolderCard ${WS_EX_TRANSPARENT}
  IntOp $0 ${SWP_NOMOVE} | ${SWP_NOSIZE}
  System::Call 'user32::SetWindowPos(p $FolderCard, p ${IXD_HWND_BOTTOM}, \
      i 0, i 0, i 0, i 0, i r0)'

  !insertmacro Pill $0 "Browse" 594 296 92 38 ${C_TEXT} ${C_SURFACE} OnBrowse
  !insertmacro Pill $0 "Cancel" 438 394 112 38 ${C_TEXT} ${C_SURFACE} GoCancel
  !insertmacro Pill $0 "Install" 560 394 132 38 ${C_WHITE} ${C_ACCENT} GoNext

  ; Show the mode MultiUser started in, rather than assuming "just me".
  ${If} $MultiUser.InstallMode == "AllUsers"
    Push 0
    Call MarkAllUsers
  ${EndIf}
  nsDialogs::Show
FunctionEnd

Function MarkAllUsers
  Pop $0
  SetCtlColors $CardAll ${C_TEXT} ${C_CARD}
  SetCtlColors $CardAllTitle ${C_TEXT} ${C_CARD}
  SetCtlColors $CardAllSub ${C_DIM} ${C_CARD}
  SetCtlColors $CardUser ${C_TEXT} ${C_SURFACE}
  SetCtlColors $CardUserTitle ${C_TEXT} ${C_SURFACE}
  SetCtlColors $CardUserSub ${C_DIM} ${C_SURFACE}
  SetCtlColors $CardAllDot ${C_ACCENT} ${C_ACCENT}
  SetCtlColors $CardUserDot ${C_FAINT} ${C_FAINT}
  Call RestateFolder
FunctionEnd

; Both handlers repaint everything belonging to a card. The labels sitting on a
; card carry their own background, and recolouring only the card left the words
; on the old colour — which reads as the panel shifting when the mode changes.
Function OnPickUser
  Pop $0
  Call MultiUser.InstallMode.CurrentUser
  SetCtlColors $CardUser ${C_TEXT} ${C_CARD}
  SetCtlColors $CardUserTitle ${C_TEXT} ${C_CARD}
  SetCtlColors $CardUserSub ${C_DIM} ${C_CARD}
  SetCtlColors $CardAll ${C_TEXT} ${C_SURFACE}
  SetCtlColors $CardAllTitle ${C_TEXT} ${C_SURFACE}
  SetCtlColors $CardAllSub ${C_DIM} ${C_SURFACE}
  SetCtlColors $CardUserDot ${C_ACCENT} ${C_ACCENT}
  SetCtlColors $CardAllDot ${C_FAINT} ${C_FAINT}
  ${NSD_SetText} $FolderText "$INSTDIR"
  Call RestateFolder
FunctionEnd

Function OnPickAll
  Pop $0
  Call MultiUser.InstallMode.AllUsers
  Push 0
  Call MarkAllUsers
  ${NSD_SetText} $FolderText "$INSTDIR"
FunctionEnd

; The folder box belongs to neither card and must not follow either of them.
; The caret is dropped as well: a box holding its selection after a click reads
; as a third colour nobody chose.
Function RestateFolder
  SetCtlColors $FolderCard ${C_SURFACE} ${C_SURFACE}
  SetCtlColors $FolderText ${C_TEXT} ${C_SURFACE}
  SendMessage $FolderText ${EM_SETSEL} 0 0
  System::Call 'user32::InvalidateRect(p $Dialog, p 0, i 1)'
FunctionEnd

Function OnBrowse
  Pop $0
  ${NSD_GetText} $FolderText $1
  nsDialogs::SelectFolderDialog "Where should it go?" "$1"
  Pop $2
  ${If} $2 != error
    ${NSD_SetText} $FolderText "$2"
  ${EndIf}
FunctionEnd

Function PageWhereLeave
  ; The box wins. The cards move it, and Browse moves it, but somebody who
  ; types a path means it — and the mode macros above rewrite $INSTDIR as a
  ; side effect, so this has to be the last word.
  ${NSD_GetText} $FolderText $0
  ${If} $0 != ""
    StrCpy $INSTDIR "$0"
  ${EndIf}
  StrCpy $Step 1
FunctionEnd

; ---------------------------------------------------------------------------
; Page two — the real install page, restyled
; ---------------------------------------------------------------------------
Function PageInstallShow
  StrCpy $Step 1
  Call HideStockButtons
  FindWindow $0 "#32770" "" $HWNDPARENT
  SetCtlColors $0 ${C_TEXT} ${C_BG}
  ; Inset to the content area, so the parent's panel colour shows down the
  ; left and the window does not change shape between pages. Controls of ours
  ; cannot be added here — nsDialogs has no dialog on this page — so this is
  ; the colour block without the step list.
  !insertmacro Place $0 ${PANEL_W} 0 470 ${WIN_H}

  GetDlgItem $1 $0 1004
  ShowWindow $1 ${SW_HIDE}
  GetDlgItem $1 $0 1006
  SetCtlColors $1 ${C_TEXT} ${C_BG}
  !insertmacro Font $1 $FontBody
  !insertmacro Place $1 34 168 402 20

  GetDlgItem $2 $0 1016
  System::Call 'uxtheme::SetWindowTheme(p $2, w " ", w " ")'
  SendMessage $2 0x0409 0 ${C_ACCENT}      ; PBM_SETBARCOLOR
  SendMessage $2 0x2001 0 ${C_SURFACE}     ; PBM_SETBKCOLOR
  !insertmacro Place $2 34 150 402 8

  GetDlgItem $3 $0 1000
  SetCtlColors $3 ${C_FAINT} ${C_BG}
  !insertmacro Font $3 $FontSmall
  !insertmacro Place $3 34 226 402 140
FunctionEnd

; ---------------------------------------------------------------------------
; Page three — done
; ---------------------------------------------------------------------------
Function PageDone
  StrCpy $Step 2
  nsDialogs::Create 1018
  Pop $Dialog
  SetCtlColors $Dialog ${C_TEXT} ${C_BG}
  Call HideStockButtons
  Call BrandPanel

  ${NSD_CreateBitmap} 0 0 10u 10u ""
  Pop $0
  ${NSD_SetImage} $0 "$PLUGINSDIR\tick.bmp" $1
  !insertmacro Place $0 284 44 36 36

  !insertmacro Label $0 "Installed" 334 44 340 30 $FontH1 ${C_TEXT} ${C_BG}
  !insertmacro Label $0 "One step left, and it is in the browser." \
      334 78 340 20 $FontBody ${C_DIM} ${C_BG}

  !insertmacro Fill $0 284 130 402 96 11 ${C_SURFACE}
  !insertmacro Label $0 "Load the extension" 302 144 370 20 $FontButton ${C_TEXT} ${C_SURFACE}
  !insertmacro Label $0 "Open chrome://extensions, turn on Developer mode and load$\r$\nthe folder beside the application. The app shows the exact path." \
      302 168 370 40 $FontSmall ${C_DIM} ${C_SURFACE}

  ; A drawn tick box: a real check box is a BUTTON, and a BUTTON paints its own
  ; face — the same reason the Browse button came out white.
  !insertmacro Fill $StartBox 284 246 18 18 5 ${C_ACCENT}
  ${NSD_OnClick} $StartBox OnToggleStart
  !insertmacro Label $0 "Start @APP_NAME@ now" 312 245 360 20 $FontBody ${C_TEXT} ${C_BG}
  ${NSD_OnClick} $0 OnToggleStart

  !insertmacro Pill $0 "Finish" 560 394 132 38 ${C_WHITE} ${C_ACCENT} GoNext
  nsDialogs::Show
FunctionEnd

Function OnToggleStart
  Pop $0
  ${If} $StartNow == 1
    StrCpy $StartNow 0
    SetCtlColors $StartBox ${C_FAINT} ${C_SURFACE}
  ${Else}
    StrCpy $StartNow 1
    SetCtlColors $StartBox ${C_ACCENT} ${C_ACCENT}
  ${EndIf}
  System::Call 'user32::InvalidateRect(p $Dialog, p 0, i 1)'
FunctionEnd

Function PageDoneLeave
  ; Launched through Explorer, so it does not inherit this installer's
  ; elevation: a child of an elevated process is elevated too, and a download
  ; manager running as administrator for the rest of the session is not what
  ; installing should cost. Explorer runs as the logged-in user.
  ${If} $StartNow == 1
    Exec '"$WINDIR\explorer.exe" "$INSTDIR\@LAUNCHER@"'
  ${EndIf}
FunctionEnd

Page custom PageWhere PageWhereLeave
Page instfiles "" PageInstallShow
Page custom PageDone PageDoneLeave

Section "Install"
  ; Close a copy that is already running, before a single file is written.
  ; The application does quit when it starts an update, but that is a race and
  ; NSIS got to the first locked file first (§437).
  DetailPrint "Closing @APP_NAME@ if it is running…"
  ExecWait 'taskkill /IM "@LAUNCHER@"'
  Sleep 2500
  ExecWait 'taskkill /IM "@LAUNCHER@" /F'
  Sleep 800

  SetOutPath "$INSTDIR"
  ; `\*` and not `\*.*`: the second is the DOS spelling and is reported to skip
  ; files with no extension.
  File /r "@PAYLOAD@\*"

  CreateDirectory "$SMPROGRAMS\@APP_NAME@"
  CreateShortCut "$SMPROGRAMS\@APP_NAME@\@APP_NAME@.lnk" "$INSTDIR\@LAUNCHER@"
  CreateShortCut "$SMPROGRAMS\@APP_NAME@\Uninstall @APP_NAME@.lnk" "$INSTDIR\uninstall.exe"
  CreateShortCut "$DESKTOP\@APP_NAME@.lnk" "$INSTDIR\@LAUNCHER@"

  ; SHCTX is HKLM for an all-users install and HKCU for a per-user one.
  ; MultiUser sets it; writing the literal hive is the mistake it exists to
  ; prevent.
  WriteRegStr SHCTX "Software\@APP_SLUG@" "InstallDir" "$INSTDIR"
  WriteRegStr SHCTX "Software\@APP_SLUG@" "InstallMode" "$MultiUser.InstallMode"
  WriteRegStr SHCTX "@UNINSTALL_KEY@" "DisplayName" "@APP_NAME@"
  WriteRegStr SHCTX "@UNINSTALL_KEY@" "DisplayVersion" "@VERSION@"
  WriteRegStr SHCTX "@UNINSTALL_KEY@" "Publisher" "@PUBLISHER@"
  WriteRegStr SHCTX "@UNINSTALL_KEY@" "DisplayIcon" "$INSTDIR\@LAUNCHER@"
  WriteRegStr SHCTX "@UNINSTALL_KEY@" "UninstallString" "$INSTDIR\uninstall.exe"
  WriteRegStr SHCTX "@UNINSTALL_KEY@" "InstallLocation" "$INSTDIR"
  WriteRegDWORD SHCTX "@UNINSTALL_KEY@" "NoModify" 1
  WriteRegDWORD SHCTX "@UNINSTALL_KEY@" "NoRepair" 1
  WriteUninstaller "$INSTDIR\uninstall.exe"

  ; An in-app update runs this silently, and a silent run has no page three to
  ; press Finish on — so it reopens the application itself, through Explorer
  ; for the same elevation reason as above.
  ${If} ${Silent}
    Exec '"$WINDIR\explorer.exe" "$INSTDIR\@LAUNCHER@"'
  ${EndIf}
SectionEnd

Section "Uninstall"
  ExecWait 'taskkill /IM "@LAUNCHER@" /F'
  Sleep 500
  Delete "$DESKTOP\@APP_NAME@.lnk"
  Delete "$SMPROGRAMS\@APP_NAME@\@APP_NAME@.lnk"
  Delete "$SMPROGRAMS\@APP_NAME@\Uninstall @APP_NAME@.lnk"
  RMDir "$SMPROGRAMS\@APP_NAME@"
  ; Takes the generated extension folders with it. They are written by the
  ; application rather than by this installer, so nothing else would.
  RMDir /r "$INSTDIR"
  DeleteRegKey SHCTX "@UNINSTALL_KEY@"
  DeleteRegKey SHCTX "Software\@APP_SLUG@"
SectionEnd
"""


def script(*, app_name: str, app_slug: str, version: str, publisher: str,
           output: str, payload: str, launcher: str, icon: str, art: str,
           uninstall_key: str) -> str:
    """The custom installer's NSIS source, with every placeholder filled in."""
    values = {
        "@APP_NAME@": app_name,
        "@APP_SLUG@": app_slug,
        "@VERSION@": version,
        "@PUBLISHER@": publisher,
        "@OUTPUT@": output,
        "@PAYLOAD@": payload,
        "@LAUNCHER@": launcher,
        "@ICON@": icon,
        "@ART@": art,
        "@UNINSTALL_KEY@": uninstall_key,
    }
    text = _SCRIPT
    for token, value in values.items():
        text = text.replace(token, value)
    return text
